require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colors")
require("user.telescope")
require("user.nvim-tree")
require("user.cmp")
require("user.treesitter")
require("user.lsp")
require("user.gitsigns")
require("user.autocommands")
require("user.autopairs")

